# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"

googleAnalytics = "G-W8XTMYPTLC"

defaultContentLanguage = "ko"

pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 100
summaryLength = 0

buildDrafts = false
buildFuture = false


[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 85
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 125

    [[related.indices]]
        name = "categories"
        weight = 75
    
    [[related.indices]]
        name = "series"
        weight = 50    

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
