build:
  writeStats: true # required by PurgeCSS.

baseURL: /
title: Hyden's Dev Blog
# Copyright, the {year} is the placeholder of this year.
copyright: "Copyright © 2022-{year} [Hugo Modules](https://hugomods.com/) and [HB Framework](https://hbstack.dev/). All Rights Reserved."
defaultContentLanguage: en
defaultContentLanguageInSubdir: false # disable this to remove the default language code from URL, i.e. /en/docs -> /docs.
enableRobotsTXT: true
timeout: 120s # images processing takes a long time, it's recommended to commit the resources folder for improve the build performance.
enableEmoji: true

title_sections: true # when false, remove the sections from the title.
title_sections_depth: 0 # the depth of sections on the title.
title_sections_depth_dir: end # when start, the depth is counting from the root sections.

permalinks:
  ai: /ai/:sections[1:]/:title/
  diary: /diary/:sections[1:]/:title/
  gallery: /gallery/:sections[1:]/:title/
  computer-science: /computer-science/:sections[1:]/:title/
  programming: /programming/:sections[1:]/:title/
  backend: /backend/:sections[1:]/:title/
  frontend: /frontend/:sections[1:]/:title/
  dev-ops: /dev-ops/:sections[1:]/:title/
  data: /data/:sections[1:]/:title/
  statistics: /statistics/:sections[1:]/:title/
  notes: /notes/:sections[1:]/:title/
  # diary: /diary/:year/:month/:title
  # gallery: /gallery/:title
  # computer-science: /computer-science/:year/:month/:title
  # programming: /programming/:year/:month/:title
  # ai: /ai/:year/:month/:title
  # backend: /backend/:year/:month/:title
  # frontend: /frontend/:year/:month/:title
  # dev-ops: /dev-ops/:year/:month/:title
  # data: /data/:year/:month/:title
  # statistics: /statistics/:year/:month/:title
  # notes: /notes/:year/:month/:title
  # page:
  #   ai: /ai/:sections/
  #   diary: /diary/:sections/
  #   gallery: /gallery/:sections/
  #   computer-science: /computer-science/:sections/
  #   programming: /programming/:sections/
  #   backend: /backend/:sections/
  #   frontend: /frontend/:sections/
  #   dev-ops: /dev-ops/:sections/
  #   data: /data/:sections/
  #   statistics: /statistics/:sections/
  #   notes: /notes/:sections/
  # section:
  #   ai: /ai/
  #   diary: /diary/
  #   gallery: /gallery/
  #   computer-science: /computer-science/
  #   programming: /programming/
  #   backend: /backend/
  #   frontend: /frontend/
  #   dev-ops: /dev-ops/
  #   data: /data/
  #   statistics: /statistics/
  #   notes: /notes/

outputs:
  home:
    - HTML
    - Offline # required by PWA module for displaying the offline pages.
    - RSS
    - SearchIndex # required by search module.
    - WebAppManifest # required by PWA module to make your site installable.
    - DecapCMSConfig

taxonomies:
  # authors: authors # multiple authors.
  tags: tags
  categories: categories
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false

# see https://gohugo.io/content-management/related/#configure-related-content
related:
  includeNewer: true
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
    - name: categories
      weight: 60
    - name: series
      weight: 60
    - name: date
      weight: 10
  threshold: 10 # for testing, increase it to suit your case.
  toLower: false

security:
  funcs:
    getenv:
      - ^HUGO
      - CI$
      - PWD
