description: 기억보다는 기록을

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    sizes:
      - size: 16x16
      - size: 32x32
      - size: 150x150
      - rel: apple-touch-icon
        size: 180x180
      - size: 192x192

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: "#712cf9"
    theme_color: "#712cf9"
    short_name: "HB Theme"

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

aos:
  css_url: https://unpkg.com/aos@next/dist/aos.css
  js_url: https://unpkg.com/aos@next/dist/aos.js

video_js:
  css_url: https://unpkg.com/video.js/dist/video-js.min.css
  js_url: https://unpkg.com/video.js/dist/video.min.js

hugomods:
  images:
    alignment_center_class_name: d-block text-center
    alignment_end_class_name: float-end ms-2
    alignment_start_class_name: float-start me-2
    class_name: img-fluid
    figure_caption_class_name: figure-caption
    figure_class_name: figure
    figure_image_class_name: figure-img
    modern_format: webp

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog:
      attributes:
        hb-blog-main-begin:
          cacheable: true
          weight: 1
    hb-blog-post-content-panel:
      hooks:
        hb-blog-post-content-end:
          weight: 1
    hb-blog-breadcrumb:
      hooks:
        hb-blog-main-begin:
          weight: 1
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
          cacheable: true
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-post-nav:
      hooks:
        hb-blog-post-content-end:
          weight: 3
    hb-blog-toc-scrollspy:
      attributes:
        hb-blog-post-content-end:
          weight: 1
          cacheable: true
    hb-blog-related-posts:
      hooks:
        hb-blog-post-content-end:
          weight: 1
          cacheable: true
    hb-blog-post-featured-image:
      hooks:
        hb-blog-post-content-begin:
          weight: 1
    hb-docs:
      attributes:
        hb-main:
          cacheable: true
      hooks:
        head-begin:
          weight: 3
        hb-header-nav-begin:
          weight: 2
    hb-header-theme-toggle:
      attributes:
        document:
          cacheable: true
      hooks:
        hb-header-panel:
          weight: 2
