baseURL = 'https://buenhyden.github.io/'
languageCode = 'ko-KR'
title = "Hyden's Dev Story'"
theme = "digitalgarden"
author = "Hyunyoun Jo"

canonifyurls = true
paginate = 10


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 3
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 4
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 5
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 6

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/buenhyden'
  weight = 1
[[menu.social]]
  name = 'Email'
  url = 'mailto:chochyjj@gmail.com'
  weight = 2
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 3


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true