baseURL = 'https://buenhyden.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "blackburn"
author = "Hyunyoun Jo"
copyright = "&copy; 2021. All rights reserved."
canonifyurls = true
paginate = 10