# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

[comments]  
  enabled = true
  provider = "giscus"

[comments.utterances]
  repo = "buenhyden/buenhyden-blog"
  issueTerm = "og:title"
  label = "Comments"

[comments.giscus]
  repo = "buenhyden/buenhyden-blog"
  repoID = "R_kgDOKeOkIg"
  category = "General"
  categoryID = "DIC_kwDOKeOkIs4CaDqE"
  mapping = "og:title"
  lightTheme = "light"
  darkTheme = "dark"
  reactionsEnabled = 1
  emitMetadata = 1
# <script src="https://giscus.app/client.js"
#         data-repo="buenhyden/buenhyden-blog"
#         data-repo-id="R_kgDOKeOkIg"
#         data-category="General"
#         data-category-id="DIC_kwDOKeOkIs4CaDqE"
#         data-mapping="og:title"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="1"
#         data-input-position="bottom"
#         data-theme="preferred_color_scheme"
#         data-lang="ko"
#         crossorigin="anonymous"
#         async>
# </script>
[firebase]
  apiKey = "AIzaSyCHVJg0xT_y8LvKX-afbnBNZB_xs6NHN80"
  authDomain = "buenhyden-blog.firebaseapp.com"
  projectId = "buenhyden-blog"
  storageBucket = "buenhyden-blog.appspot.com"
  messagingSenderId = "15921042518"
  appId = "1:15921042518:web:c26614a99aefb390b2d7f7"
  measurementId = "G-W8XTMYPTLC"

