baseURL: https://buenhyden.github.io/
# see https://hugomods.com/en/docs/google-analytics/.
googleAnalytics: "G-RBYWSZ3QZX" # Google Analytics, please make sure you've imported the Google Analytics module.

# disqusShortname: XXXXXX # The Disqus shortname.
