# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters
[comments]
  enabled = true
  provider = "giscus"

[comments.disqusjs]
  shortname = "buenhyden/buenhyden.github.io"
  apiUrl = "title"
  apiKey = "Comments"
  admin = ""
  adminLabel=""

[comments.utterances]
  repo = "buenhyden/buenhyden.github.io"
  issueTerm = "og:title"
  label = "Comments"

[comments.giscus]
  repo = "buenhyden/buenhyden.github.io"
  repoID = "R_kgDOKa2JLg"
  category = "General"
  categoryID = "DIC_kwDOKa2JLs4CaDqK"
  mapping = "og:title"
  lightTheme = "light"
  darkTheme = "dark"
  reactionsEnabled = 1
  emitMetadata = 1
#   <script src="https://giscus.app/client.js"
#         data-repo="buenhyden/buenhyden.github.io"
#         data-repo-id="R_kgDOKa2JLg"
#         data-category="General"
#         data-category-id="DIC_kwDOKa2JLs4CaDqK"
#         data-mapping="og:title"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="1"
#         data-input-position="bottom"
#         data-theme="dark"
#         data-lang="ko"
#         crossorigin="anonymous"
#         async>
# </script>
  
[firebase]
  apiKey = "AIzaSyCHVJg0xT_y8LvKX-afbnBNZB_xs6NHN80"
  authDomain = "buenhyden-blog.firebaseapp.com"
  projectId = "buenhyden-blog"
  storageBucket = "buenhyden-blog.appspot.com"
  messagingSenderId = "15921042518"
  appId = "1:15921042518:web:c26614a99aefb390b2d7f7"
  measurementId = "G-W8XTMYPTLC"
